import { QuoteStatus } from '@prisma/client';

export const ALLOWED_QUOTE_TRANSITIONS: Record<QuoteStatus, QuoteStatus[]> = {
  NEW: ['REVIEWING', 'REJECTED', 'CANCELLED'],
  REVIEWING: ['CONTACTED', 'PROPOSAL_SENT', 'REJECTED', 'CANCELLED'],
  CONTACTED: ['PROPOSAL_SENT', 'REJECTED', 'CANCELLED'],
  PROPOSAL_SENT: ['NEGOTIATION', 'APPROVED', 'REJECTED', 'CANCELLED'],
  NEGOTIATION: ['APPROVED', 'REJECTED', 'CANCELLED'],
  APPROVED: ['COMPLETED', 'CANCELLED'],
  REJECTED: [],
  COMPLETED: [],
  CANCELLED: []
};
